<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="James Livsey and Christoph Sax">
<title>7&nbsp; SEATS – Seasonal Adjustment in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./30-part-data-problems.html" rel="next">
<link href="./24-x11.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed6da6eef3892af8a4b5ed59bfb951f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><meta name="robots" content="noindex">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<style>
.tag {
    display: inline-block;
    padding: 0.2em 0.4em;
    margin-right: 0.5em;
    font-size: 0.85em;
    color: white;
    border-radius: 0.25em;
}

.tag-case-study {
    background-color: green;
}

.tag-frequency {
    background-color: orange;
}

.tag-fundamentals {
    background-color: blue;
}

.tag-exercises {
    background-color: grey;
}



</style>
<script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./20-part-basics.html">Basics</a></li><li class="breadcrumb-item"><a href="./25-seats.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SEATS</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Seasonal Adjustment in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/christophsax/seasonalbook.content" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Getting started</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./20-part-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The fundamentals of X-13</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-transform.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Transform</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-regARIMA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">regARIMA Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-x11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">X-11</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-seats.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SEATS</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./30-part-data-problems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Problems</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-holidays.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Irregular holidays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32-trading-days.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Trading days</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33-outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Outliers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34-seasonal-breaks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Seasonal breaks</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./40-part-other-issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other Issues</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41-presence-of-seasonality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Presence of seasonality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42-annual-constraining.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Annual constraining</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43-indirect-vs-direct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Indirect vs direct adjustment</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./50-part-quality-assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quality assessment</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./51-quality-measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Quality measures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./52-revisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Revisions</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#basics" id="toc-basics" class="nav-link active" data-scroll-target="#basics"><span class="header-section-number">7.1</span> Basics</a></li>
  <li><a href="#arima-model-decompostion" id="toc-arima-model-decompostion" class="nav-link" data-scroll-target="#arima-model-decompostion"><span class="header-section-number">7.2</span> ARIMA Model decompostion</a></li>
  <li><a href="#comparing-seats-with-x-11-filters" id="toc-comparing-seats-with-x-11-filters" class="nav-link" data-scroll-target="#comparing-seats-with-x-11-filters"><span class="header-section-number">7.3</span> Comparing SEATS with X-11 filters</a></li>
  <li>
<a href="#advanced-theory" id="toc-advanced-theory" class="nav-link" data-scroll-target="#advanced-theory"><span class="header-section-number">7.4</span> Advanced theory</a>
  <ul class="collapse">
<li><a href="#quick-refresher-on-arima-models-and-notation" id="toc-quick-refresher-on-arima-models-and-notation" class="nav-link" data-scroll-target="#quick-refresher-on-arima-models-and-notation"><span class="header-section-number">7.4.1</span> Quick refresher on ARIMA models and notation</a></li>
  <li><a href="#seats-assumptions" id="toc-seats-assumptions" class="nav-link" data-scroll-target="#seats-assumptions"><span class="header-section-number">7.4.2</span> SEATS Assumptions</a></li>
  <li><a href="#sec-canonical-decomposition" id="toc-sec-canonical-decomposition" class="nav-link" data-scroll-target="#sec-canonical-decomposition"><span class="header-section-number">7.4.3</span> Canonical Decomposition</a></li>
  <li><a href="#sec-wiener-kolmogorov-algorithm" id="toc-sec-wiener-kolmogorov-algorithm" class="nav-link" data-scroll-target="#sec-wiener-kolmogorov-algorithm"><span class="header-section-number">7.4.4</span> Wiener-Kolmogorov Algorithm</a></li>
  <li><a href="#transitory-component" id="toc-transitory-component" class="nav-link" data-scroll-target="#transitory-component"><span class="header-section-number">7.4.5</span> Transitory component</a></li>
  </ul>
</li>
  <li><a href="#case-study-narrow-seats-filters" id="toc-case-study-narrow-seats-filters" class="nav-link" data-scroll-target="#case-study-narrow-seats-filters"><span class="header-section-number">7.5</span> Case study: narrow SEATS filters</a></li>
  <li><a href="#considerations-when-using-seats-in-x-13" id="toc-considerations-when-using-seats-in-x-13" class="nav-link" data-scroll-target="#considerations-when-using-seats-in-x-13"><span class="header-section-number">7.6</span> Considerations when using SEATS in X-13</a></li>
  <li>
<a href="#sec-comparing" id="toc-sec-comparing" class="nav-link" data-scroll-target="#sec-comparing"><span class="header-section-number">7.7</span> Comparing X-11 and SEATS</a>
  <ul class="collapse">
<li><a href="#seats-filters-from-seas-output" id="toc-seats-filters-from-seas-output" class="nav-link" data-scroll-target="#seats-filters-from-seas-output"><span class="header-section-number">7.7.1</span> SEATS filters from <code>seas</code> output</a></li>
  <li><a href="#reasons-for-using-seats-or-x11" id="toc-reasons-for-using-seats-or-x11" class="nav-link" data-scroll-target="#reasons-for-using-seats-or-x11"><span class="header-section-number">7.7.2</span> Reasons for using SEATS or X11</a></li>
  </ul>
</li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">7.8</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/christophsax/seasonalbook.content/edit/main/25-seats.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/christophsax/seasonalbook.content/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./20-part-basics.html">Basics</a></li><li class="breadcrumb-item"><a href="./25-seats.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SEATS</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-seats" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">SEATS</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.seasonal.website">seasonal</a></span><span class="op">)</span></span>
<span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span><span class="va">AirPassengers</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; seas(x = AirPassengers)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                     Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; Weekday           -0.0029497  0.0005232  -5.638 1.72e-08 ***</span></span>
<span><span class="co">#&gt; Easter[1]          0.0177674  0.0071580   2.482   0.0131 *  </span></span>
<span><span class="co">#&gt; AO1951.May         0.1001558  0.0204387   4.900 9.57e-07 ***</span></span>
<span><span class="co">#&gt; MA-Nonseasonal-01  0.1156204  0.0858588   1.347   0.1781    </span></span>
<span><span class="co">#&gt; MA-Seasonal-12     0.4973600  0.0774677   6.420 1.36e-10 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 144  Transform: log</span></span>
<span><span class="co">#&gt; AICc: 947.3, BIC: 963.9  QS (no seasonality in final):    0  </span></span>
<span><span class="co">#&gt; Box-Ljung (no autocorr.): 26.65   Shapiro (normality): 0.9908</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<!--

  Nest time:

  - Christoph to rework, and hold SEATS part. Once I am fine with that, the chapter has the right level
  - 7.1 and 7.2 are already quite good, 7.3 is tiny
  - 7.4 optionally left to Jim (if time allows)
  - Some more hammering on the intiution



  # What is the definition of Seasonality?
  What is the role of predictability?




 -->
<p>In the previous chapter, we got to know X-11, a seasonal decomposition procedure that utilizes predefined moving-average filters. SEATS, which we will get to know in this chapter, derives its filters from the underlying ARIMA model.</p>
<section id="basics" class="level2 page-columns page-full" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="basics">
<span class="header-section-number">7.1</span> Basics</h2>
<p>Signal Extraction in ARIMA Time Series, or SEATS, is a method for estimating unobserved components in a time series. It is developed from the work of <span class="citation" data-cites="cleveland76">Cleveland and Tiao (<a href="#ref-cleveland76" role="doc-biblioref">1976</a>)</span>, <span class="citation" data-cites="hillmer82">Hillmer and Tiao (<a href="#ref-hillmer82" role="doc-biblioref">1982</a>)</span>, <span class="citation" data-cites="maravall86">Maravall (<a href="#ref-maravall86" role="doc-biblioref">1986</a>)</span>. If applied properly, SEATS seasonal factors are usually more stable than X-11, and the seasonally adjusted series show less revisions than X11 (see <a href="#sec-comparing" class="quarto-xref"><span>Section 7.7</span></a> for a more extensive discussion).</p>
<div class="no-row-height column-margin column-container"><div id="ref-cleveland76" class="csl-entry" role="listitem">
Cleveland, William P, and George C Tiao. 1976. <span>“Decomposition of Seasonal Time Series: A Model for the Census x-11 Program.”</span> <em>Journal of the American Statistical Association</em> 71 (355): 581–87.
</div><div id="ref-hillmer82" class="csl-entry" role="listitem">
Hillmer, S. C., and G. C. Tiao. 1982. <span>“An ARIMA-Model-Based Approach to Seasonal Adjustment.”</span> <em>Journal of the American Statistical Association</em> 77 (377): 63–70. <a href="http://www.jstor.org/stable/2287770">http://www.jstor.org/stable/2287770</a>.
</div><div id="ref-maravall86" class="csl-entry" role="listitem">
Maravall, Agustin. 1986. <span>“Revisions in ARIMA Signal Extraction.”</span> <em>Journal of the American Statistical Association</em> 81 (395): 736–40. <a href="http://www.jstor.org/stable/2289005">http://www.jstor.org/stable/2289005</a>.
</div></div><p>Like X-11, SEATS applies a series of filters to an observed time series, as described in <a href="24-x11.html" class="quarto-xref"><span>Chapter 6</span></a>. Like X-11, SEATS uses a forecast extended series, in order to obtain unbiased results at the margin. Unlike X-11, however, SEATS filters are derived from the ARIMA model of the time series. While X-11 filters are predefined and fixed, the SEATS filters are different for each ARIMA model.</p>
<p>While X-11 offers a finite set of filters, <!-- (in fact, there are seven seasonal filters available),  --> SEATS offers an infinite set of filters. Overall, they cover a broader set of possible filter lengths, which makes SEATS a more flexible option than X-11. The available set filter lengths is the most crucial difference between X-11 and SEATS. At the same time, the additional flexibility may lead at times to filters that are undesirable. As will be shown later on, SEATS sometimes choose a filter that is too narrow, and produces an overly volatile seasonal component.</p>
<!--
Let's compare X-11 and SEATS filters

#### X-11 filters {.unnumbered}

-   finite set of empirically developed moving average filters
-   fixed filtering seen as easier to use (less statistical machinery)

#### SEATS filters {.unnumbered}

-   specifies stochastic models for unobserved components
-   derives seasonal adjustment filters from these models
-   infinite number of possible filter choices
-   requires more statistical machinery

 -->
<p>To perform a SEATS seasonal adjustment in R, you can use the following code:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span><span class="va">AirPassengers</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; seas(x = AirPassengers)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                     Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; Weekday           -0.0029497  0.0005232  -5.638 1.72e-08 ***</span></span>
<span><span class="co">#&gt; Easter[1]          0.0177674  0.0071580   2.482   0.0131 *  </span></span>
<span><span class="co">#&gt; AO1951.May         0.1001558  0.0204387   4.900 9.57e-07 ***</span></span>
<span><span class="co">#&gt; MA-Nonseasonal-01  0.1156204  0.0858588   1.347   0.1781    </span></span>
<span><span class="co">#&gt; MA-Seasonal-12     0.4973600  0.0774677   6.420 1.36e-10 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 144  Transform: log</span></span>
<span><span class="co">#&gt; AICc: 947.3, BIC: 963.9  QS (no seasonality in final):    0  </span></span>
<span><span class="co">#&gt; Box-Ljung (no autocorr.): 26.65   Shapiro (normality): 0.9908</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As long as SEATS and X-11 use similar filters, the final adjustment will be similar. Using the default arguments of <code><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas()</a></code> on <code>AirPassengers</code>, the adjustment is very similar:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m_x11</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span><span class="va">AirPassengers</span>, x11 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu">tsbox</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/tsbox/reference/ts_plot.html">ts_plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/final.html">final</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/final.html">final</a></span><span class="op">(</span><span class="va">m_x11</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>We will look into the similarities between SEATS and X-11 in section …</p>
</section><section id="arima-model-decompostion" class="level2" data-number="7.2"><h2 data-number="7.2" class="anchored" data-anchor-id="arima-model-decompostion">
<span class="header-section-number">7.2</span> ARIMA Model decompostion</h2>
<p>Given a certain ARIMA model (such as the “Airline” <code>(0 1 1)(0 1 1)</code> which is appropriate for the description of the <code>AirPassengers</code> time series), SEATS decomposes the model into separate models for the trend, the seasonal and the irregular component. This is done by the <em>Canonical Decomposition</em> and will be discussed in <a href="#sec-canonical-decomposition" class="quarto-xref"><span>Section 7.4.3</span></a>.</p>
<p>For a given set of ARIMA model parameter, the decomposition of the ARIMA model is almost independent of the data. For each ARIMA specification, there is a unique canonical decomposition. For an “Airline” <code>(0 1 1)(0 1 1)</code> model (with both moving average coefficients not being to close to 1), the trend component can be described with a <code>(0 2 2)(0 0 0)</code> model, while the seasonal sum of seasonal component can be described by a <code>(0 0 11)(0 0 0)</code> model. The parameters of these models can be derived from the parameter estimates of the initial airline model that describes the original series. The irregular component is usually white noise, described by the trivial <code>(0 0 0)(0 0 0)</code> model.</p>
<p>The decomposed ARIMA models imply a certain filter, which is derived by the Wiener-Kolmogorov procedure (<a href="#sec-wiener-kolmogorov-algorithm" class="quarto-xref"><span>Section 7.4.4</span></a>).</p>
</section><section id="comparing-seats-with-x-11-filters" class="level2 page-columns page-full" data-number="7.3"><h2 data-number="7.3" class="anchored" data-anchor-id="comparing-seats-with-x-11-filters">
<span class="header-section-number">7.3</span> Comparing SEATS with X-11 filters</h2>
<p><span class="citation" data-cites="planas02">Planas and Depoutot (<a href="#ref-planas02" role="doc-biblioref">2002</a>)</span> systematically compare SEATS and X-11 filters and show which X11 seasonal filter that is closest to an implied <code>(0 1 1)(0 1 1)</code> “Airline” SEATS model based on the <span class="math inline">\(\Theta\)</span>. As a reminder, <span class="math inline">\(\Theta\)</span> refers to the seasonal moving average parameter of the ARIMA model.</p>
<div class="no-row-height column-margin column-container"><div id="ref-planas02" class="csl-entry" role="listitem">
Planas, Christophe, and Raoul Depoutot. 2002. <span>“Controlling Revisions in Arima-Model-Based Seasonal Adjustment.”</span> <em>Journal of Time Series Analysis</em> 23 (2): 193–213.
</div></div><table class="caption-top table">
<thead><tr class="header">
<th>Filter</th>
<th>Closest Seasonal MA</th>
<th>Seasonal MA Interval</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>3x3</td>
<td>0.364 - 0.400</td>
<td>0.0 - 0.5</td>
</tr>
<tr class="even">
<td>3x5</td>
<td>0.543 - 0.563</td>
<td>0.51 - 0.74</td>
</tr>
<tr class="odd">
<td>3x9</td>
<td>0.723 - 0.732</td>
<td>0.75 - 0.87</td>
</tr>
<tr class="even">
<td>3x15</td>
<td>0.824 - 0.828</td>
<td>0.88 - 1.00</td>
</tr>
</tbody>
</table>
<p>Let’s consider small vs large values of seasonal <span class="math inline">\(\Theta\)</span>. Values of <span class="math inline">\(\Theta\)</span> close to zero yield a seasonal adjustment filter that has seasonal factors that change rapidly over time. This provides considerable smoothing and large revisions. These revisions will only last for a small number of years due to the shorter filters.</p>
<p>Values of <span class="math inline">\(\Theta\)</span> close to one yield a seasonal adjustment filter that has seasonal factors that change slowly over time. This provides less smoothing but relatively small revisions. Any revisions that do occur will last for a longer period of time due to the longer filters.</p>
<p>Overall, we may think of SEATS filters as a broader, more flexible set of filters than X-11 filers. While we have just seven filters in X-11, we have an infinite number of filters in SEATS. They cover a larger range of filters spans, ranging from filters that are much narrower than X-11 to filters that are much wider.</p>
<p>SEATS greatest strength is also its greatest weakness. As we will see in the example below, SEATS sometimes chooses a filter that is very narrow. From a SEATS perspective, this makes sense: Given an ARIMA model with a very weak seasonality, the filter lengths should be chooses narrowly. From a practical perspective, the resulting seasonal component is undesirable. It is too volatile, essentially catching much of the irregular component and making the resulting seasonally adjusted series too smooth.</p>
<!-- Additionally, the filters that are -->
</section><section id="advanced-theory" class="level2" data-number="7.4"><h2 data-number="7.4" class="anchored" data-anchor-id="advanced-theory">
<span class="header-section-number">7.4</span> Advanced theory</h2>
<section id="quick-refresher-on-arima-models-and-notation" class="level3" data-number="7.4.1"><h3 data-number="7.4.1" class="anchored" data-anchor-id="quick-refresher-on-arima-models-and-notation">
<span class="header-section-number">7.4.1</span> Quick refresher on ARIMA models and notation</h3>
<p>The remaining of the SEATS section will heavily rely on the auto-regressive and moving-average operators <span class="math inline">\(\phi(B)\)</span> and <span class="math inline">\(\theta(B)\)</span> where <span class="math inline">\(B X_t = X_{t-1}\)</span>.</p>
<p>If <span class="math inline">\(X_t\)</span> follows and ARIMA(<span class="math inline">\(p\)</span>, <span class="math inline">\(d\)</span>, <span class="math inline">\(q\)</span>) model: <span class="math display">\[
\phi(B) X_t = \theta(B) a_t
\]</span></p>
<p><span class="math display">\[
(1 - \phi_1 B - \cdots - \phi_p B^p)(1-B)^d X_t = (1 + \theta_1 B + \cdots \theta_q B^q) a_t
\]</span></p>
<p>For example, in an ARIMA(2,0,1) we are modeling <span class="math inline">\(X_t\)</span> as:</p>
<p><span class="math display">\[
X_t = \phi_1 X_{t-1} + \phi_2 X_{t-2} + a_t + \theta_1 a_{t-1}
\]</span></p>
<p>and all model information is contained in <span class="math inline">\(\phi(B)\)</span> and <span class="math inline">\(\theta(B)\)</span>. Moreover, for any specified <span class="math inline">\(\phi(B)\)</span> and <span class="math inline">\(\theta(B)\)</span> that satisfy certain causality criteria there exists a unique Wold decomposition <span class="math display">\[
\phi(B) X_t = \theta(B) a_t
\]</span></p>
<p><span class="math display">\[
X_t = \frac{\theta(B)}{\phi(B)} a_t = \Psi(B) a_t = \sum_{k=0}^{\infty} \psi_k a_{t-k}
\]</span></p>
</section><section id="seats-assumptions" class="level3" data-number="7.4.2"><h3 data-number="7.4.2" class="anchored" data-anchor-id="seats-assumptions">
<span class="header-section-number">7.4.2</span> SEATS Assumptions</h3>
<ul>
<li>The linearized series can be represented by an ARIMA model which captures the stochastic structure of the series. As a reminder, the linearized series is the series with regression effects removed.</li>
<li>After differencing each with the ARIMA’s differencing polynomial, the components are orthogonal (uncorrelated)</li>
</ul>
<p>SEATS decomposes the auto-regressive polynomial by its roots associating them with different latent components. For example, roots near seasonal frequencies are associated with the seasonal component and roots near zero are associated with the trend component. <span class="math display">\[
\phi(B) = \phi_T(B) \cdot \phi_S(B) \cdot \phi_R(B).
\]</span></p>
<p>Hence we have, <span class="math display">\[
X_t =
\frac{\theta(B)}{\phi(B)} a_{t} =
\frac{\theta_T(B)}{\phi_T(B)} a_{T,t} +
\frac{\theta_S(B)}{\phi_S(B)} a_{S,t}  +
\frac{\theta_R(B)}{\phi_R(B)} a_{R,t}  + u_t
\]</span></p>
<p>If the spectra of all components in non-negative the decomposition is admissible, SEATS finds admissible models for components <span class="math display">\[ \phi_T(B) T_t = \theta_T(B) a_{T, t} \]</span> <span class="math display">\[ \phi_S(B) S_t = \theta_S(B) a_{S, t} \]</span> <span class="math display">\[\phi_R(B) R_t = \theta_R(B) a_{R, t} \]</span></p>
</section><section id="sec-canonical-decomposition" class="level3" data-number="7.4.3"><h3 data-number="7.4.3" class="anchored" data-anchor-id="sec-canonical-decomposition">
<span class="header-section-number">7.4.3</span> Canonical Decomposition</h3>
<p>However, there infinite number of models that yield the same aggregate. The choices differ in how white noise is allocated among the components. This is where the <em>Canonical Decomposition</em> comes into play. SEATS uses the method of Pierce, Box-Hillmer, Tiao and Burman:</p>
<ul>
<li>Put all the white noise into the irregular components</li>
<li>Maximize the variance of the irregular</li>
<li>Minimizes the variance of the stationary transforms of the other components</li>
</ul>
<p>This is called the <em>Canonical Decomposition</em>. We already stated that both X-11 and SEATS estimate the unobserved components by passing a moving-average filter over the observed data. So how do we use these implied component models to get a linear filter? It should be clear that the filter weights will depend on that arima model is picked <span class="math inline">\(X_t = \Psi(B) a_t\)</span>, and what the implied seasonal model, <span class="math inline">\(\phi_S(B) S_t = \theta_S(B) a_{S,t} \Rightarrow S_t = \Psi(B) a_t\)</span>, is.</p>
</section><section id="sec-wiener-kolmogorov-algorithm" class="level3" data-number="7.4.4"><h3 data-number="7.4.4" class="anchored" data-anchor-id="sec-wiener-kolmogorov-algorithm">
<span class="header-section-number">7.4.4</span> Wiener-Kolmogorov Algorithm</h3>
<p>The <strong>Wiener-Kolmogorov</strong> (WK) algorithm outlines the methodology to get the so-called WK filter. This is the filter that is equal to the conditional expectation of the seasonal component conditional on the observed series.</p>
<p><span class="math display">\[\widehat{S}_t = \underbrace{\left[ \frac{\Sigma_S}{\Sigma} \frac{\Psi_S(B)\Psi_S(F)}{\Psi(B)\Psi(F)} \right]}_{\mbox{WK filter weights}} X_t\]</span> where <span class="math inline">\(F=B^{-1}\)</span> if the forward shift operator such that <span class="math inline">\(F X_t = X_{t+1}\)</span>.</p>
<p>More than other coefficients, the seasonal MA (<span class="math inline">\(\theta_{12}\)</span>) influences whether estimated seasonal factors change either slowly over time (<span class="math inline">\(\theta_{12}\)</span> close to 1) or rapidly over time (<span class="math inline">\(\theta_{12}\)</span> close to zero).</p>
</section><section id="transitory-component" class="level3" data-number="7.4.5"><h3 data-number="7.4.5" class="anchored" data-anchor-id="transitory-component">
<span class="header-section-number">7.4.5</span> Transitory component</h3>
<p>Sometimes SEATS includes a transitory component in its decomposition:</p>
<p><span class="math display">\[ X_t = T_t + S_t + R_t + I_t \]</span></p>
<p>The transitory component captures short, erratic behavior that is not white noise, sometimes associated with awkward frequencies.</p>
<ul>
<li>The variation from the transitory component should not contaminate the trend or seasonal, and removing it allows SEATS to obtain smoother, more stable trends and seasonal components.</li>
<li>In the final decomposition, the transitory and irregular components are usually combined.</li>
<li>SEATS does not always estimate a transitory component</li>
</ul></section></section><section id="case-study-narrow-seats-filters" class="level2" data-number="7.5"><h2 data-number="7.5" class="anchored" data-anchor-id="case-study-narrow-seats-filters">
<span class="header-section-number">7.5</span> Case study: narrow SEATS filters</h2>
<p><span class="tag tag-case-study"><i class="fas fa-graduation-cap"></i> Case Study</span></p>
<p>Let’s have a look at nominal taxes from Swiss production account.</p>
<p>The series looks as follows:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span></span>
<span><span class="fu">ts_plot</span><span class="op">(</span><span class="va">tax_n</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="co"># static(seas(tax_n))</span></span>
<span></span>
<span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="va">tax_n</span>,</span>
<span>  regression.variables <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"easter[15]"</span><span class="op">)</span>,</span>
<span>  arima.model <span class="op">=</span> <span class="st">"(0 1 1)(1 0 0)"</span>,</span>
<span>  regression.aictest <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>  outlier <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>  transform.function <span class="op">=</span> <span class="st">"none"</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>While the summary looks fine,</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; seas(x = tax_n, transform.function = "none", regression.aictest = NULL, </span></span>
<span><span class="co">#&gt;     outlier = NULL, regression.variables = c("easter[15]"), arima.model = "(0 1 1)(1 0 0)")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                     Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; Easter[15]        -213.82083   63.50954  -3.367 0.000761 ***</span></span>
<span><span class="co">#&gt; AR-Seasonal-04       0.47697    0.09087   5.249 1.53e-07 ***</span></span>
<span><span class="co">#&gt; MA-Nonseasonal-01    0.63304    0.07859   8.055 7.98e-16 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; SEATS adj.  ARIMA: (0 1 1)(1 0 0)  Obs.: 102  Transform: none</span></span>
<span><span class="co">#&gt; AICc:  1442, BIC:  1452  QS (no seasonality in final):    0  </span></span>
<span><span class="co">#&gt; Box-Ljung (no autocorr.): 17.27   Shapiro (normality): 0.9833</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>the seasonal factors seem erratic:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/monthplot.html">monthplot</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>To me (Christoph), this seems against the very basic idea of seasonal adjustment: We want to collect predictable fluctuations in the seasonal component, not random noise. The other side of the coin is a very smooth seasonal adjustment.</p>
<p>These kind of SI-ratios appear in around 10 to 20% of SEATS adjustment and may be the reason why SEATS often seems smoother than X11.</p>
<p>How to detect these cases? How to deal with these adjustments?</p>
</section><section id="considerations-when-using-seats-in-x-13" class="level2" data-number="7.6"><h2 data-number="7.6" class="anchored" data-anchor-id="considerations-when-using-seats-in-x-13">
<span class="header-section-number">7.6</span> Considerations when using SEATS in X-13</h2>
<p>Some model limitations when using SEATS are as follows.</p>
<ul>
<li>SEATS does not accept missing lag models. Hence, it is acceptable to specify a (0 1 3)(0 1 1) model but unacceptable to specify (0 1 [1 3])(0 1 1).</li>
<li>The AR and MA orders (p and q) cannot be greater than 3.</li>
<li>
<em>Inadmissible decomposition</em>: Sometimes, the estimated values of coefficients make it impossible to estimate components from the estimated ARIMA models. SEATS will usually change the model and re-estimate it in order to get an admissible decomposition. When it is difficult to find an admissible decomposition the airline model is often used as a replacement. This usually gives acceptable results for a broad range of series.</li>
<li>Model span can have large implications in a SEATS adjustment. This is due to the changing dynamics of long time series and how SEATS derives its filters.</li>
</ul></section><section id="sec-comparing" class="level2" data-number="7.7"><h2 data-number="7.7" class="anchored" data-anchor-id="sec-comparing">
<span class="header-section-number">7.7</span> Comparing X-11 and SEATS</h2>
<p>The Bureau of Labor Statistics formed a group to do a comparison study between X-11 and model-based seasonal adjustments (CITE BLS 2007). The examined a cross section of 87 BLS series with X-11, SEATS, and STAMP using spectral, revisions history, model adequacy and sliding spans diagnostics. They found that SEATS seasonal factors are usually more stable than X-11 and X-11 trend component is usually more stable than SEATS. Also, among series that were seasonal, residual seasonality almost never appears using either method.</p>
<p>The only exception being a small number of SEATS runs where model inadequacy for the full span of data was present. This manifested as SEATS having difficulty identifying a usable model for decomposition and falling back on the airline model. They found even in these situations the SEATS seasonal adjustment is usually reasonable.</p>
<p>Overall, X-11 and SEATS seasonal adjustments are very similar for many series. SEATS adjustments are often smoother than X-11 seasonal adjustments. For some series, the variance can be different based on the month or season. For example, U.S. Housing Starts is more variable in the winter months than in the summer due to the differences in warm and cold winters. ARIMA model-based seasonal adjustment does not handle this situation very well and assumes a constant variance and the SEATS adjustment wont compensate for this.</p>
<section id="seats-filters-from-seas-output" class="level3" data-number="7.7.1"><h3 data-number="7.7.1" class="anchored" data-anchor-id="seats-filters-from-seas-output">
<span class="header-section-number">7.7.1</span> SEATS filters from <code>seas</code> output</h3>
<p>The trend filter and seasonal adjustment filter can be extracted from the output of a <code>seasonal</code> run. This is done via the <strong>save</strong> argument in the seats spec. In the following example the symmetric trend filter is saved and then exported. Note the <code>finite='yes'</code> argument must be specified to save filter weights.</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span><span class="va">AirPassengers</span>,</span>
<span>          seats.finite <span class="op">=</span> <span class="st">'yes'</span>,</span>
<span>          seats.save   <span class="op">=</span> <span class="st">'ftf'</span>, <span class="co"># symmetric finite trend filter</span></span>
<span>          out          <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">ftf_file</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">wdir</span>, <span class="st">'iofile.ftf'</span><span class="op">)</span></span>
<span><span class="co"># reads in filter weights from ftf_file</span></span>
<span><span class="va">w</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.delim</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/textconnections.html">textConnection</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/readLines.html">readLines</a></span><span class="op">(</span><span class="va">ftf_file</span><span class="op">)</span><span class="op">[</span><span class="op">-</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>,</span>
<span>                header <span class="op">=</span> <span class="cn">TRUE</span>, stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="op">-</span><span class="fl">72</span><span class="op">:</span><span class="fl">71</span>, <span class="va">w</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span>, type <span class="op">=</span> <span class="st">"l"</span>,</span>
<span>     xlab <span class="op">=</span> <span class="st">""</span>,</span>
<span>     ylab <span class="op">=</span> <span class="st">"weights"</span>,</span>
<span>     main <span class="op">=</span> <span class="st">"SEATS trend filter"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>The default SEATS output tables do not allow users to save the seasonal filter, only the seasonal adjustment and trend filters. Some additional work can be done to calculate the seasonal filters via the canonical decomposition implied models and the Wiener-Kolmogorov algorithm. The code provided here is a bit complicated and will be improved/modularized in subsequent version of this textbook. It involves outputting the <code>mdc</code> table and the using the <code>grep</code> functions to extract salient features for each model component. The naming conventions for the <code>mdc</code> table follow the Wald decomposition notation where moving average components appear in the numerator and differencing and/or autoregressive components appear in the denominator. The following assumes there are no AR components and anything appearing in the denominator is attributed to the differencing operator.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/seasonal/man/seas.html">seas</a></span><span class="op">(</span><span class="va">AirPassengers</span>,</span>
<span>          outlier <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>          regression.aictest <span class="op">=</span> <span class="cn">NULL</span>,</span>
<span>          arima.model <span class="op">=</span> <span class="st">'(0 1 1)(0 1 1)'</span>,</span>
<span>          seats.save <span class="op">=</span> <span class="st">'mdc'</span>,</span>
<span>          out <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">m</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; seas(x = AirPassengers, regression.aictest = NULL, outlier = NULL, </span></span>
<span><span class="co">#&gt;     out = TRUE, arima.model = "(0 1 1)(0 1 1)", seats.save = "mdc")</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;                   Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; MA-Nonseasonal-01  0.40182    0.07887   5.095 3.49e-07 ***</span></span>
<span><span class="co">#&gt; MA-Seasonal-12     0.55694    0.07626   7.303 2.80e-13 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; SEATS adj.  ARIMA: (0 1 1)(0 1 1)  Obs.: 144  Transform: log</span></span>
<span><span class="co">#&gt; AICc: 987.4, BIC: 995.8  QS (no seasonality in final):    0  </span></span>
<span><span class="co">#&gt; Box-Ljung (no autocorr.): 28.04   Shapiro (normality): 0.9886  </span></span>
<span><span class="co">#&gt; Messages generated by X-13:</span></span>
<span><span class="co">#&gt; Warnings:</span></span>
<span><span class="co">#&gt; - At least one visually significant seasonal peak has been</span></span>
<span><span class="co">#&gt;   found in the estimated spectrum of the regARIMA residuals.</span></span>
<span><span class="co">#&gt; - At least one visually significant trading day peak has been</span></span>
<span><span class="co">#&gt;   found in one or more of the estimated spectra.</span></span>
<span></span>
<span><span class="va">decomp.m</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.delim</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span><span class="op">(</span><span class="va">m</span><span class="op">$</span><span class="va">wdir</span>, <span class="st">'iofile.mdc'</span><span class="op">)</span>, sep <span class="op">=</span> <span class="st">':'</span>,</span>
<span>                       stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span>, header <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">decomp.m</span><span class="op">)</span></span>
<span><span class="co">#&gt;           V1           V2</span></span>
<span><span class="co">#&gt; 1     ntcnum  3.000000000</span></span>
<span><span class="co">#&gt; 2  tcnum.000  1.000000000</span></span>
<span><span class="co">#&gt; 3  tcnum.001  0.047518134</span></span>
<span><span class="co">#&gt; 4  tcnum.002 -0.952481866</span></span>
<span><span class="co">#&gt; 5     ntcden  3.000000000</span></span>
<span><span class="co">#&gt; 6  tcden.000  1.000000000</span></span>
<span><span class="co">#&gt; 7  tcden.001 -2.000000000</span></span>
<span><span class="co">#&gt; 8  tcden.002  1.000000000</span></span>
<span><span class="co">#&gt; 9      tcvar  0.054007671</span></span>
<span><span class="co">#&gt; 10     nsnum 12.000000000</span></span>
<span><span class="co">#&gt; 11  snum.000  1.000000000</span></span>
<span><span class="co">#&gt; 12  snum.001  1.412938279</span></span>
<span><span class="co">#&gt; 13  snum.002  1.485031335</span></span>
<span><span class="co">#&gt; 14  snum.003  1.412580521</span></span>
<span><span class="co">#&gt; 15  snum.004  1.216865960</span></span>
<span><span class="co">#&gt; 16  snum.005  0.970661608</span></span>
<span><span class="co">#&gt; 17  snum.006  0.704452210</span></span>
<span><span class="co">#&gt; 18  snum.007  0.440934873</span></span>
<span><span class="co">#&gt; 19  snum.008  0.218194121</span></span>
<span><span class="co">#&gt; 20  snum.009  0.009565283</span></span>
<span><span class="co">#&gt; 21  snum.010 -0.126641925</span></span>
<span><span class="co">#&gt; 22  snum.011 -0.415452995</span></span>
<span><span class="co">#&gt; 23     nsden 12.000000000</span></span>
<span><span class="co">#&gt; 24  sden.000  1.000000000</span></span>
<span><span class="co">#&gt; 25  sden.001  1.000000000</span></span>
<span><span class="co">#&gt; 26  sden.002  1.000000000</span></span>
<span><span class="co">#&gt; 27  sden.003  1.000000000</span></span>
<span><span class="co">#&gt; 28  sden.004  1.000000000</span></span>
<span><span class="co">#&gt; 29  sden.005  1.000000000</span></span>
<span><span class="co">#&gt; 30  sden.006  1.000000000</span></span>
<span><span class="co">#&gt; 31  sden.007  1.000000000</span></span>
<span><span class="co">#&gt; 32  sden.008  1.000000000</span></span>
<span><span class="co">#&gt; 33  sden.009  1.000000000</span></span>
<span><span class="co">#&gt; 34  sden.010  1.000000000</span></span>
<span><span class="co">#&gt; 35  sden.011  1.000000000</span></span>
<span><span class="co">#&gt; 36      svar  0.054246235</span></span>
<span><span class="co">#&gt; 37    nsanum  3.000000000</span></span>
<span><span class="co">#&gt; 38 sanum.000  1.000000000</span></span>
<span><span class="co">#&gt; 39 sanum.001 -1.365780650</span></span>
<span><span class="co">#&gt; 40 sanum.002  0.393702700</span></span>
<span><span class="co">#&gt; 41    nsaden  3.000000000</span></span>
<span><span class="co">#&gt; 42 saden.000  1.000000000</span></span>
<span><span class="co">#&gt; 43 saden.001 -2.000000000</span></span>
<span><span class="co">#&gt; 44 saden.002  1.000000000</span></span>
<span><span class="co">#&gt; 45     savar  0.625661730</span></span>
<span><span class="co">#&gt; 46    irrvar  0.297766039</span></span>
<span></span>
<span><span class="co"># trend-cycle model</span></span>
<span><span class="va">macoefs</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^tcnum'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">trend.var</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span> <span class="op">==</span> <span class="st">'tcvar'</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span><span class="va">trendDiff</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^tcden'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># seasonal model</span></span>
<span><span class="va">seasonal.macoefs</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^snum'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">seasonal.var</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span> <span class="op">==</span> <span class="st">'svar'</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span><span class="va">seasonalDiff</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^sden'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># irregular variance</span></span>
<span><span class="va">irr.var</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span> <span class="op">==</span> <span class="st">'irrvar'</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># transitory model (usually not needed)</span></span>
<span><span class="va">trans.macoefs</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^trnum'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">trans.var</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span> <span class="op">==</span> <span class="st">'trvar'</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span><span class="va">transDiff</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^trden'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span></span>
<span><span class="co"># seasonally adjusted model</span></span>
<span><span class="va">sadj.macoefs</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^sanum'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span><span class="op">[</span><span class="op">-</span><span class="fl">1</span><span class="op">]</span></span>
<span><span class="va">sadj.var</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span> <span class="op">==</span> <span class="st">'savar'</span>,<span class="st">'V2'</span><span class="op">]</span></span>
<span><span class="va">sadjDiff</span> <span class="op">&lt;-</span> <span class="va">decomp.m</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span><span class="op">(</span><span class="st">'^saden'</span>, <span class="va">decomp.m</span><span class="op">$</span><span class="va">V1</span><span class="op">)</span>,<span class="st">'V2'</span><span class="op">]</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To further understand these components the implied trend model is the following:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">macoefs</span></span>
<span><span class="co">#&gt; [1]  0.04751813 -0.95248187</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which tells us the trend is an MA(2) with coefficients <span class="math inline">\(\theta_1 = 0.04751813\)</span> and <span class="math inline">\(\theta_2 = -0.95248187\)</span>. The variance of the innovations, <span class="math inline">\(\sigma\)</span> is</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trend.var</span></span>
<span><span class="co">#&gt; [1] 0.05400767</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and the differencing is</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">trendDiff</span></span>
<span><span class="co">#&gt; [1]  1 -2  1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>which is second differencing, i.e.&nbsp;<span class="math inline">\(\delta(B) = 1 - 2B + B^2 = (1-B)^2\)</span>.</p>
<p>We can use these component models to apply the WK algorithm and get the seasonal filter weights. The details of this complex operation are omitted here but a plot of the seasonal filter weights is given in Figure ???.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="25-seats_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section><section id="reasons-for-using-seats-or-x11" class="level3" data-number="7.7.2"><h3 data-number="7.7.2" class="anchored" data-anchor-id="reasons-for-using-seats-or-x11">
<span class="header-section-number">7.7.2</span> Reasons for using SEATS or X11</h3>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TODO
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add Table with pros and cons</p>
</div>
</div>
<p>First off, there does not exist a simple flow chat that tells each individual users whether they should use SEATS or X-11. For most well-behaved series both methods will produce suitable seasonal adjustments that will work for the majority of use cases. The ultimate decision between the two comes down to a few questions.</p>
<ol type="1">
<li>What will you be doing with these seasonal adjustments?</li>
<li>How often is your data revised?</li>
<li>Does your agency have a policy to freeze data/seasonal adjustment revisions after a fixed period of time?</li>
<li>How much time can be devoted to development of initial spec files?</li>
<li>How much time can be devoted to maintenance of spec files?</li>
<li>What is your maintenance schedule? (yearly, monthly, etc)</li>
<li>What are the consequences of a poor adjustment?</li>
<li>What are the consequences of large revisions?</li>
<li>Will your agency be publishing original series, just SA, trends, seasonal factors?</li>
<li>Is there an emphasis on deep methodological understanding of the procedures?</li>
<li>Is there an emphasis on training users of released data to have a methodological understanding of the SA process?</li>
</ol>
<ul>
<li><p>When applied properly (good ARIMA model, filters are not too narrow), it produces a seasonal component that is more stable. This leads to less revisions in the resulting series.</p></li>
<li><p>When applied improperly (bad ARIMA model, narrow filters), it produces an unpredictable seasonal component and an overly smooth seasonally adjusted series.</p></li>
<li><p>X-11 is more ‘robust’: If applied without additional checks. If this is desirable it may be a better option.</p></li>
<li><p>If you check SEATS models carefully, it may produce a more stable adjustment.</p></li>
</ul>
<p>To sum up, whether you should use SEATS or X11 also depends on how much work you are willing to invest in a series.</p>
</section></section><section id="exercises" class="level2" data-number="7.8"><h2 data-number="7.8" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">7.8</span> Exercises</h2>
<p><span class="tag tag-exercises"><i class="fas fa-shoe-prints"></i> Exercises</span></p>



</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/christophsax\.github\.io\/seasonalbook\.content");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./24-x11.html" class="pagination-link" aria-label="X-11">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">X-11</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./30-part-data-problems.html" class="pagination-link" aria-label="Data Problems">
        <span class="nav-page-text">Data Problems</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>by James Livsey and Christoph Sax</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/christophsax/seasonalbook.content/edit/main/25-seats.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/christophsax/seasonalbook.content/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Seasonal Adjustment in R</p>
</div>
  </div>
</footer>


</body></html>