# Outliers {#sec-outliers}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
status("drafting") # drafting, polishing, complete
```

<!-- -   Why care about outliers? -->

<!-- -   Additive outliers, level shifts, temporary changes -->

## Introduction

Exceptional data value, or outliers may constitute a problem both for the ARIMA model building as well as for the sesonal filtering.
When analyzing time series data, outlier values are common.
In some cases, these issues can be linked to actual events in the real world, such as:

- the COVID-19 pandamemic
- the 2008/09 financial market crash
- Natural disasters
- Ukraine crisis

These events can impact the accuracy of seasonal adjustment. As a result, X-13 tries to remove these inconsistencies before performing seasonal adjustment.

X-13 offers several ways to model outliers. In this chapter, we will focus on two most important types of effects that can occur in time series data: level shifts and additive outliers. By understanding these effects and how to address them, analysts can improve the quality of their analyses and draw more accurate conclusions from the data.



## Level Shift

The first outlier category we look at are level shifts. Level shifts refers to a sudden and sustained change in the underlying level of a time series.
Theree can be various causes of level shifts in time series data, such as changes in concepts or definitions of the survey population, alterations in the method of data collection, shifts in economic behavior, changes in legislation, etc. Below is an example of a level shift:

TODO


Level shifts are a problem for seasonal adjustment because they will distort the estimation of the seasonal factors.



Within X-13, the initial trend is calculated by applying a moving average to the series. If there is an abrupt change in the level of the series, the estimates will be distorted. The estimates before the level shift will be underestimated, and those after will be overestimated. As the calculation of the irregular and seasonal components follow on from this initial trend-cycle estimation, they may be distorted as well.

TODO explain example




## Level Shift

The first outlier category we look at are level shifts. Level shifts refers to a sudden and sustained change in the underlying level of a time series.
Theree can be various causes of level shifts in time series data, such as changes in concepts or definitions of the survey population, alterations in the method of data collection, shifts in economic behavior, changes in legislation, etc. Below is an example of a level shift:

TODO


Level shifts are a problem for seasonal adjustment because they will distort the estimation of the seasonal factors.



Within X-13, the initial trend is calculated by applying a moving average to the series. If there is an abrupt change in the level of the series, the estimates will be distorted. The estimates before the level shift will be underestimated, and those after will be overestimated. As the calculation of the irregular and seasonal components follow on from this initial trend-cycle estimation, they may be distorted as well.

TODO explain example





## Additive Outliers

An additive outlier is a data point that falls outside the general pattern of the trend and seasonal component in a time series. Outliers can be caused by random effects, such as an extreme irregular point, or by identifiable factors, such as a strike or bad weather.

Additive outliers pose a significant challenge to seasonal adjustment methods, which rely on moving averages. The crux of the problem lies in the inherent sensitivity of averages to the presence of extreme values or outliers. When unusual data points are included, the average can become unrepresentative of the underlying pattern in the series. Without proper adjustments or allowances for outliers, estimates for all the components in a time series can become distorted. As such, addressing additive outliers is critical to maintaining the integrity of seasonal adjustment techniques and ensuring accurate analyses.



TODO example

Seasonally adjusting the data above, without allowing for the outliers, gives the following results:

TODO


## Identifiying Outliers

X-13 contains an outomated outlier detection procedure that works well in most circumstances and can be used as a starting poing. Plotting the series may add additional information on wheter outliers should be adjusted or not.

TODO

series{title="Example of level shift and outlier search"
       start=1994.1
       period=4
       file="mydata.txt"}
arima{model=(0,1,1)(0,1,1)}
outlier{types=(ao ls)
        span=(2002.2, )
x11{mode=mult}

The outlier specification in the arima model allows for automatic detection of level shifts and additive outliers, either individually or in combination. Once identified, the outliers are incorporated into the model as "Automatically Identified Outliers" along with appropriate regression variables.

It's important to note that this specification has some limitations. Specifically, it can only detect outliers with a high critical value for their t-statistics. The critical value used depends on the number of observations searched for outliers. For instance, if the search is conducted for the last year of data, the critical value is 3.16, which is higher than the standard critical value of 1.96. Consequently, outliers with t-statistics between 1.96 and 3.16 may not be detected with this option.

Therefore, it's crucial to conduct visual checks of the NSA and SA series to identify any outliers that might have been missed by the automatic detection process. For more information on the default critical values for outlier identification, refer to the X-13 Reference Manual.







## Additional tools to identify outliers

Idenfifying level shifts and additive outliers is no always as obvious as in the example above.
The following tables may help to identify the level shifts and additive outliers

TODO (From ONS Manual)

- Look at Table E5 and E6 in the output?
These tables show the month- on-month (or quarter-on-quarter) changes in the original and seasonally adjusted estimates. In fact, a level shift will appear as a sudden large increase which is not followed by a corresponding decrease (or vice versa) in Table E5 and E6. The adjustment for the level shift effectively attempts to remove this sudden change in the level.

- Additive outliers can be detected by analysing Table C17 and D13 in addition to Table E5 and E6 in the output. In fact, an additive outlier will appear as one or more zeros in the period of the outlier in Table C17, which gives the final weights for the irregular component, and as a residual pattern of the irregular component presented in Table D13. In addition to inspecting these four output tables, M1, M2 and M3 statistics should be checked. M1, M2 and M3 each measure the level of the irregular component in the series compared to the trend and the seasonal components. If these fail it may indicate that outliers need to be replaced as temporary prior adjustments.


## Confirming the reason for the level shifts or the additive outliers

TODO (From ONS Manual)

If the X-12-ARIMA test and the graphs of the NSA and SA series lead you to suspect a level shift or an outlier, then check which months/quarters it appears in. Question if there is any evidence for suspecting a level shift or outlier at this time point.
If there is not a methodological, social or economic reason to explain the presence of the suspected level
shift or outlier then do not adjust for it.



