project:
  type: book
  output-dir: _book

book:
  title: "Seasonal Adjustment in R"
  reader-mode: true
  downloads: [pdf]
  page-footer:
    left: |
      by James Livsey and Christoph Sax
    right: |
      Seasonal Adjustment in R
  site-url: https://christophsax.github.io/seasonalbook.content
  repo-url: https://github.com/christophsax/seasonalbook.content
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - part: index.qmd
      chapters:
        - 10-introduction.qmd
        - 11-minimal-example.qmd
        - 12-how-to-use.qmd

    - part: 20-part-basics.qmd
      chapters:
        - 21-overview.qmd
        - 22-transform.qmd
        - 25-regARIMA.qmd
        - 23-seats.qmd
        - 24-x11.qmd

    - part: 30-part-data-problems.qmd
      chapters:
        - 31-holidays.qmd
        - 32-trading-days.qmd
        - 33-outliers.qmd
        - 34-seasonal-breaks.qmd

    - part: 40-part-other-issues.qmd
      chapters:
        - 41-presence-of-seasonality.qmd
        - 42-annual-constraining.qmd
        - 43-indirect-vs-direct.qmd

    - part: 50-part-quality-assessment.qmd
      chapters:
        - 51-quality-measures.qmd
        - 52-revisions.qmd

    - part: 60-part-future.qmd
      chapters:
        - 99-status.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
    code-link: true
    include-in-header: "header.html"
    author-meta: "James Livsey and Christoph Sax"
    callout-appearance: simple

  pdf: default

editor: visual

editor_options:
  markdown:
    wrap: sentence
    canonical: true

